
import express from "express";
import AuthRoutes from './AuthRoutes.js';
import ClientRoutes from './ClientRoutes.js';
import DriverRoutes from './DriverRoutes.js';
import VehicleRoutes from './VehicleRoutes.js';
import RulesRoutes from './Rules.js';
import CategoryRoutes from './CategoryRoutes.js';
import ServiceRoutes from './ServiceRoutes.js';
import RideRoutes from './RideRoute.js';
import DishRoutes from './DishRoutes.js';
import OrderRoutes from './OrderRoutes.js';
import CartRoutes from './CartRoutes.js';
import WalletRoutes from './WalletRoutes.js';
import RatingRoutes from './RatingRoutes.js';
import TaxRoutes from './TaxRoutes.js';
import ZoneRoutes from './ZoneRoutes.js';
import RestuarantRoutes from './RestaurantRoutes.js';
import BankRoutes from './BankRoutes.js';
import ChatRoutes from './ChatRoutes.js';
import NotificationRoutes from './NotificationRoute.js';
import PaymentRoutes from './PaymentRoutes.js';
import RewardRoutes from './RewardRoutes.js';
const router = express.Router(); router.use("/auth", AuthRoutes);
router.use("/bank", BankRoutes);
router.use("/cart", CartRoutes);
router.use("/category", CategoryRoutes);
router.use("/client", ClientRoutes);
router.use("/dish", DishRoutes);
router.use("/driver", DriverRoutes);
router.use("/order", OrderRoutes);
router.use("/ride", RideRoutes);
router.use("/restaurant", RestuarantRoutes);
router.use("/reviews", RatingRoutes);
router.use("/rules", RulesRoutes);
router.use("/services", ServiceRoutes);
router.use("/tax", TaxRoutes);
router.use("/vehicles", VehicleRoutes);
router.use("/wallet", WalletRoutes);
router.use("/zone", ZoneRoutes);
router.use("/chat", ChatRoutes);
router.use("/notification", NotificationRoutes);
router.use("/payment", PaymentRoutes);
router.use("/reward", RewardRoutes);
export default router;